ASP.NET MVC/WebApplication1/WebApplication1/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication2.Models;

namespace WebApplication1.Controllers
{
    public class EmployeeController : Controller
    {
        static List<Employee> employees = new List<Employee>();

        //GET : /Employee/Detail
        //[HttpGet]
        public IActionResult Index()
        {
            if (employees.Count == 0)
            {
                for (int i = 1; i < 15; i++)
                {
                    Employee employee = new Employee
                    {
                        Id = i,
                        Name = "Personel Adı",
                        Surname = "Soyadı " + i,
                        Durumu = i % 2 == 0 ? false : true,
                        Gorev = i % 2 == 0 ? Gorevler.Developer : Gorevler.TeamLead
                    };

                    employees.Add(employee);
                }
            }


            return View(employees);
        }


        //GET : /Employee/Detail/1
        public IActionResult Detail(int id)
        {
            //select top 1 e.* from dbo.Employees as e where e.EmployeeId=1
            Employee employee = employees.Where(x => x.Id == id).FirstOrDefault();
            ViewBag.kullaniciAdi = "aykut.bastug";
            ViewBag.personel = employee;
            ViewBag.sayi = 43;


            ViewData["kullaniciAdi"] = employee.Name + " " + employee.Surname;


            return View(employee);
        }


        //GET : /Employee/Create
        public IActionResult Create()
        {
            return View();
        }

        //GET
        //POST => Kayıt ekleme işlemleri için data post etmeye yarar
        //PUT => Güncelleme işlemleri için data post etmeye yarar
        //DELETE => Silme işlemeleri için kullanılır
        //PATH => Post ve put un birleşimi
        [HttpPost]
        public IActionResult Create(Employee model)
        {
            if (ModelState.IsValid)
            {
                if (employees.Count(x => x.Id == model.Id) == 0)
                {
                    employees.Add(model);
                    //return View("Index", employees);
                    //return RedirectToAction("Index");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Girilen değer sistemde kayıtlı");
                    return View(model);
                }

            }
            else
            {
                return View(model);
            }
        }


        //GET : /Employee/Edit/1
        public IActionResult Edit(int id)
        {
            Employee employee = employees.Where(x => x.Id == id).FirstOrDefault();


            return View(employee);
        }

        [HttpPost]
        public IActionResult Edit(Employee model)
        {
            if (ModelState.IsValid)
            {
                int index = employees.IndexOf(employees.Find(e => e.Id == model.Id));
                employees[index] = model;

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
           
        }


        //GET : /Employee/Delete/1
        public IActionResult Delete(int id)
        {
            Employee employee = employees.Where(x => x.Id == id).FirstOrDefault();


            return View(employee);
        }

        //POST : /Employee/Delete
        [HttpPost]
        public IActionResult Delete(int id, Employee model)
        {
            Employee employee = employees.Where(x => x.Id == id).FirstOrDefault();
            employees.Remove(employee);

            return RedirectToAction(nameof(Index));
        }

    }
}

ASP.NET MVC/WebApplication1/WebApplication1/Controllers/KisiController.cs
using ImageMagick;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class KisiController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _environment;
        SqlConnection connection = new SqlConnection();

        public KisiController(IConfiguration configuration, IWebHostEnvironment environment)
        {
            _configuration = configuration;
            connection.ConnectionString = _configuration.GetConnectionString("Rehber");
            _environment = environment;
        }

        public IActionResult Index()
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Kisiler", connection);
            DataTable dt = new DataTable();
            da.Fill(dt);

            List<Kisi> Kisiler = new List<Kisi>();
            foreach (DataRow row in dt.Rows)
            {
                Kisiler.Add(new Kisi
                {
                    Id = Convert.ToInt32(row["Id"].ToString()),
                    ImageUrl = row["ImageUrl"].ToString(),
                    Name = row["Name"].ToString(),
                    Phone = row["Phone"].ToString(),
                    Surname = row["Surname"].ToString()
                });
            }


            return View(Kisiler);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Kisi model, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                model.ImageUrl = CopyFile(file);

                SqlCommand cmd = new SqlCommand("insert into dbo.Kisiler values (@Name, @Surname, @Phone, @ImageUrl)", connection);
                cmd.Parameters.AddWithValue("Name", model.Name);
                cmd.Parameters.AddWithValue("Surname", model.Surname);
                cmd.Parameters.AddWithValue("Phone", model.Phone);
                cmd.Parameters.AddWithValue("ImageUrl", model.ImageUrl);

                connection.Open();
                cmd.ExecuteNonQuery();
                connection.Close();

                return RedirectToAction(nameof(Index));
            }
            else
                return View(model);
        }


        public IActionResult Details(int id)
        {
            Kisi kisi = GetKisi(id);

            return View(kisi);
        }

        private Kisi GetKisi(int id)
        {
            SqlDataAdapter dataAdapter = new SqlDataAdapter("select * from dbo.Kisiler where Id=@KisiId", connection);
            dataAdapter.SelectCommand.Parameters.AddWithValue("KisiId", id);

            DataTable dataTable = new DataTable();
            dataAdapter.Fill(dataTable);

            Kisi kisi = new Kisi
            {
                Id = Convert.ToInt32(dataTable.Rows[0]["Id"].ToString()),
                ImageUrl = dataTable.Rows[0]["ImageUrl"].ToString(),
                Name = dataTable.Rows[0]["Name"].ToString(),
                Phone = dataTable.Rows[0]["Phone"].ToString(),
                Surname = dataTable.Rows[0]["Surname"].ToString()
            };
            return kisi;
        }

        public IActionResult Edit(int id)
        {
            return View(GetKisi(id));
        }

        [HttpPost]
        public IActionResult Edit(Kisi model, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                if (file == null)
                    model.ImageUrl = GetKisi(model.Id).ImageUrl;
                else
                    model.ImageUrl = CopyFile(file);

                SqlCommand cmd = new SqlCommand("update dbo.Kisiler set Name=@Name, Surname=@Surname, Phone=@Phone, ImageUrl=@ImageUrl where Id=@Id", connection);
                cmd.Parameters.AddWithValue("Id", model.Id);
                cmd.Parameters.AddWithValue("Name", model.Name);
                cmd.Parameters.AddWithValue("Surname", model.Surname);
                cmd.Parameters.AddWithValue("Phone", model.Phone);
                cmd.Parameters.AddWithValue("ImageUrl", model.ImageUrl);


                //if (file == null)
                //{
                //    SqlCommand cmd = new SqlCommand("update dbo.Kisiler set Name=@Name, Surname=@Surname, Phone=@Phone where Id=@Id", connection);
                //    cmd.Parameters.AddWithValue("Id", model.Id);
                //    cmd.Parameters.AddWithValue("Name", model.Name);
                //    cmd.Parameters.AddWithValue("Surname", model.Surname);
                //    cmd.Parameters.AddWithValue("Phone", model.Phone);
                //}
                //else
                //{
                //    model.ImageUrl = CopyFile(file);

                //    SqlCommand cmd = new SqlCommand("update dbo.Kisiler set Name=@Name, Surname=@Surname, Phone=@Phone, ImageUrl@ImageUrl where Id=@Id", connection);
                //    cmd.Parameters.AddWithValue("Id", model.Id);
                //    cmd.Parameters.AddWithValue("Name", model.Name);
                //    cmd.Parameters.AddWithValue("Surname", model.Surname);
                //    cmd.Parameters.AddWithValue("Phone", model.Phone);
                //    cmd.Parameters.AddWithValue("ImageUrl", model.ImageUrl);
                //}

                connection.Open();
                cmd.ExecuteNonQuery();
                connection.Close();

                return RedirectToAction(nameof(Index));
            }
            else
                return View(model);
        }

        private string CopyFile(IFormFile file)
        {
            string wwwRootPath = _environment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(file.FileName);
            string extension = Path.GetExtension(file.FileName);
            string newFileName = fileName + DateTime.Now.ToString("yyMMddmmssfff") + extension;

            string path = Path.Combine(wwwRootPath + "/uploads/", newFileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                file.CopyTo(fileStream);
            }


            MagickImage imageBig = new MagickImage(path);
            MagickGeometry sizeBig = new MagickGeometry(800, 400);
            //imageBig.Resize(800, 400);
            imageBig.Resize(sizeBig);
            imageBig.Quality = 40;

            string newFileNameBig = fileName + DateTime.Now.ToString("yyMMddmmssfff") + "_800_400" + extension;
            imageBig.Write(Path.Combine(wwwRootPath + "/uploads/", newFileNameBig));


            return newFileName;
        }


        public IActionResult Delete(int id)
        {
            return View(GetKisi(id));
        }

        [HttpPost]
        public IActionResult Delete(Kisi model)
        {
            string wwwRootPath = _environment.WebRootPath;
            string path = Path.Combine(wwwRootPath + "/uploads/", GetKisi(model.Id).ImageUrl);
            System.IO.File.Delete(path);


            SqlCommand cmd = new SqlCommand("delete from dbo.Kisiler where Id=@Id", connection);
            cmd.Parameters.AddWithValue("Id", model.Id);

            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();            

            return RedirectToAction(nameof(Index));
        }
    }
}

ASP.NET MVC/WebApplication1/WebApplication1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Urunler()
        {
            return View();
        }

        public IActionResult UrunDetay()
        {
            return View();
        }
    }
}

ASP.NET MVC/WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="About" >Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Urunler">Ürün Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="UrunDetay">Ürün Detay</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Personel Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Kisi" asp-action="Index">Rehber</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.AddYears(1).Year - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>